{ config, inputs, pkgs, ... }:
let
  fenix = inputs.fenix.packages.${pkgs.system};
  username = config.modules.other.system.username;
in {
    environment.systemPackages = with pkgs; [
            alacritty
            alsa-utils
            android-tools
            asciinema
            bibata-cursors
            blanket
            blugon
            dig
            dmenu
            easyeffects
            element-desktop
            eza
            fastfetch
            feh
            (fenix.complete.withComponents [
              "cargo"
              "clippy"
              "rust-src"
              "rustc"
              "rustfmt"
            ])
            ffmpeg-full
            fftw
            flameshot
            foot
            gcc
            gdb
            gnumake
            grimblast
            git
            httpie
            i3lock
            imagemagickBig
            img2pdf
            keepassxc
            krita
            lazygit
            libreoffice-fresh
            librewolf
            links2
            moc
            ncmpcpp
            neofetch
            neovim
            networkmanagerapplet
            nextcloud-client
            nicotine-plus
            nitrogen
            pamixer
            pavucontrol
            picom
            pcmanfm
            pdfarranger
            pfetch
            playerctl
            polkit
            python3
            qbittorrent
            ripgrep
            rustdesk
            rofi
            scc
            scrot
            sherlock
            signal-desktop-beta
            smartmontools
            spotube
            steam
            strawberry
            telegram-desktop
            texliveFull
            trilium-desktop
            thunderbird
            tor-browser-bundle-bin
            trash-cli
            tree
            unzip
            util-linux
            ventoy-full
            vlc
            weechat
            wget
            wireguard-tools 
            xclip
            xfce.thunar
            xorg.libX11.dev
            xorg.libXft
            xorg.libXinerama
            xournalpp
            yt-dlp
            zathura
            zip
        ];
}
