# add_newline = false

format = """
\$directory
\${custom.separator}
"""

[directory]
format = '[$path/]($style)'
truncate_length = 2
truncate_to_repo = false
use_logical_pat = true
style = "fg:cyan"
truncate_symbol = "../"
disabled = false

[custom.separator]
format = "[ ||| ]($style)"
style = "fg:purple"
disabled = false
