name: Flake Check

on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4
      - name: Install Nix
        uses: https://github.com/DeterminateSystems/nix-installer-action@v5
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Check
        run: nix flake check
