[directory]
style = "bold cyan"
read_only = " "
truncate_to_repo = false
#truncation_length = 0
format = "[󰉋 $path]($style)([$read_only]($read_only_style))"
#repo_root_style = "red"
home_symbol = "~"
#disabled = true

